#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    sum=0
    num1,num2=0,1
    while num2<n:
        if(num2%2==0):
            sum+=num2
        num1,num2=num2,num1+num2
    print(sum)
        
        
