#!/bin/python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 25 13:00:25 2018

@author: Abhay Kagalkar - CodesExplorer
"""

t=int(input().strip())
for a0 in range(t):
    result=0
    n,m=input().strip().split(" ")
    n,m=[int(n),int(m)]
    for i in range(1,n+1):
        result+=(i%m)
    print(result)    
